---

# this is some black magic to:
# 1. check if NZBHydra has the indexer configured based on its name
# 2. if it is configured then grab it's index in the list
# 3. update the dictionary key/values in that list index to match vars
# 4. if doesn't exist, append it to the indexers list

- name: Init list index variable
  set_fact:
    indexer_configured_index: ''

- name: Find {{ nzbhydra_indexer_item['name'] }} in Indexers and store its index in the list
  set_fact:
    indexer_configured_index: "{{ indexer_configured_index_loop }}"
  loop: "{{ current_configured_indexers.result }}"
  loop_control:
    index_var: indexer_configured_index_loop
  when:
    - current_configured_indexers.result | selectattr('name', 'match', nzbhydra_indexer_item['name']) | list | count > 0
    - item['name'] == nzbhydra_indexer_item['name']

- name: Debug index
  debug:
    var: indexer_configured_index

- name: Configure indexer if exists using its index in the list
  yedit:
    src: "{{ nzbhydra_config_directory }}/nzbhydra.yml"
    key: "indexers.[{{ indexer_configured_index }}].{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ nzbhydra_indexer_item | dict2items }}"
  when: indexer_configured_index != ''

- name: Append indexer to list if not found
  yedit:
    src: "{{ nzbhydra_config_directory }}/nzbhydra.yml"
    key: "indexers"
    value: "{{ nzbhydra_indexer_item }}"
    append: true
  when: indexer_configured_index == ''
